modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "shriek"
version = "${version}"
displayName = "Shriek"
authors = "Pryzmm"
description = '''
A Minecraft Voice Recognition Library (Maintained from ModogTheDev)
'''
logoFile = "assets/shriek/icon.png"

[[dependencies.shriek]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shriek]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shriek]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "shriek.mixins.json"
