modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "voicelib"
version = "${version}"
displayName = "VoiceLib"
authors = "ModogTheDev"
description = '''
A Minecraft Voice Recognition Library
'''
logoFile = "assets/voicelib/icon.png"

[[dependencies.voicelib]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.voicelib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.voicelib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "voicelib.mixins.json"
